services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env

  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api

networks:
  grace:
    driver: bridge